### ISSUE TITLE
Unable to find an entry point named 'pinvoke_get_string_length' in shared library 'imobiledevice'.

### ISSUE THREAD

**Issue by awakenitsme** [master131/iFakeLocation#69]
"Unable to find an entry point named 'pinvoke_get_string_length' in shared library 'imobiledevice'." this is what i get when i try to refresh devices.

terminal log:
<a href="https://ibb.co/K7bfHxq"><img src="https://i.ibb.co/rMFzJ26/Screenshot-2022-01-11-15-16-52.png" alt="Screenshot-2022-01-11-15-16-52" border="0"></a>

**Comment by master131** [comment]
Are you using Linux? What distro is it?

**Comment by awakenitsme** [comment]
yes. I'm using an debian distro.

**Comment by master131** [comment]
It appears to be a known issue with one of the core libraries used to interact with iDevices on Linux but I am not sure what the fix is. 

https://github.com/libimobiledevice-win32/imobiledevice-net/issues/12
https://github.com/libimobiledevice-win32/imobiledevice-net/issues/144

I do remeber I tested this on Ubuntu without issue; I believe the library author targets Ubuntu 16.04 so if you are using a different Linux distro there could be subtle compatibility issues.

**Comment by bababash** [comment]
This is the solution:

https://github.com/libimobiledevice/libimobiledevice/issues/1067#issuecomment-960507331

Now I need to figure out why my iphone isn't coming up on the list...
